### ISSUE TITLE
2021 7월 1주차 TODO

### ISSUE THREAD

**Issue by yeomko22** [yeomko22/TIL#84]
- [ ] dependency injection 공부, 개념 정리
- [ ] python coroutine, eventloop, python에서의 비동기 처리 공부
- [ ] SOLID 패턴 관련 예제 코드 살펴보고 정리할 것
