### ISSUE TITLE
7 / 6 TODO

### ISSUE THREAD

**Issue by yeomko22** [yeomko22/TIL#86]
- [x] leetcode medium 1 문제 풀기
- [x] 블로그에 알고리즘 문제 풀이 간단히 작성하기
- [ ] solid, 디자인 패턴 관련 책 선정하고, single responsibility 관련 내용 숙지하기
- [ ] srcp 최신 모델 학습, 데이터 뽑기
- [ ] shopping SAS fetch spec 코드 작성하기
