### ISSUE TITLE
21. 7. week3 TODO

### ISSUE THREAD

**Issue by yeomko22** [yeomko22/TIL#89]
## 7. 15. Thu
- [ ] (work) get srcp experiment results and analysis
- [ ] (algorithm) solve 2+ leetcode problems
- [ ] (mlops) start read kubeflow book (~ch 4.) and summarize it
- [ ] (stock) summarize book I read yesterday
- [ ] (exercise) 100 push ups 30 pull ups

**Comment by yeomko22** [comment]
7. 16. Fri
### TODO
- [ ] (work) finish analyze fn nx true cases
- [ ] (algorithm) solve 2+ leetcode problems
- [ ] (mlops) install kubeflow, practive sample questions of mlops book
- [ ] (stock) review the parts I read and summarize it

**Comment by yeomko22** [comment]
## 7. 17. Sat
### TODO
- [ ] (algorithm) solve 2+ leetcode problems
- [ ] (mlops) build kubernetes cluster on ncloud infrastructures
- [ ] (mlops) install kubeflow on kubernetes cluster
- [ ] (stock) reread and summarize

**Comment by yeomko22** [comment]
## 7. 19.
- [ ] (work) start review quickwit (search engine based on rust)
- [ ] (work) build kubeflow cluster
- [ ] (work) update newest fn list
- [ ] (algorithm) solve 2+problems
- [ ] (stock) reread book
- [ ] (exercies) run +5 km, 100 push ups, 30 pull ups
