### ISSUE TITLE
20210719 ~ 20210725 TODO

### ISSUE THREAD

**Issue by yeomko22** [yeomko22/TIL#90]
## Weekly Plan
- [ ] (work) finish srcp project
- [ ] (work) review quickwit
- [ ] (work) study kubeflow
- [ ] (stock) finish reading stock price book(미국 주식으로 부자되기) 2 times and summarize it. Do real practice
- [ ] (mlops) finish read kubeflow book
- [ ] (algorithm) solve +10 leetcode problems
- [ ] (exercies) run +5km on everyday morning, 100 push ups, 30 pull ups

**Comment by yeomko22** [comment]
## 7. 19. Mon
- [ ] (work) start review quickwit (search engine based on rust)
- [ ] (work) build kubeflow cluster
- [ ] (work) update newest fn list
- [ ] (algorithm) solve 2+problems
- [ ] (stock) reread book
- [ ] (exercies) run +5 km, 100 push ups, 30 pull ups

**Comment by yeomko22** [comment]
## 7. 20. Tue
- [ ] (work) finish implement fetch of shopping npp
- [ ] (algorithm) solve 2+ leetcode problems
- [ ] (mlops) build kubeflow environemnt
- [ ] (stock) reread and summarize ch 4~5 of the book
- [ ] (exercise) run +5 km at morning, 100 push ups, 30 pull ups

**Comment by yeomko22** [comment]
## 7. 21. Wed
- [x] (work) Install and follow the tutorials of quickwit
- [x] (algorithm) solve 2+ leetcode problems
- [ ] (mlops) build kubeflow environemnt
- [x] (stock) reread and summarize ch 4~5 of the book
- [x] (exercise) run +5 km at morning, 100 push ups, 30 pull ups

**Comment by yeomko22** [comment]
## 7. 22. Thu
- [ ] (work)
- [ ] (algorithm) solve 2+ algorithm
- [ ] (mlops) take andrew ng deep learning course on youtube
- [ ] (exercise) run +5km 120 pushups 40 pullups 100 squarts

**Comment by yeomko22** [comment]
## 7. 23. Fri
- [x] (work) implement srcp API rules
- [x] (algorithm) solve 2+ algorithm
- [ ] (mlops) take andrew ng deep learning course on youtube
- [ ] (exercise) run +5km 120 pushups 40 pullups 100 squarts
- [ ] (stock) summarize sillicon vally book
- [ ] (side-project) code refactoring of previous codes
