### ISSUE TITLE
20210727-20210801

### ISSUE THREAD

**Issue by yeomko22** [yeomko22/TIL#91]
## Weekly Goals
- [ ] use ML serving stacks
- [ ] take all helm courses

**Comment by yeomko22** [comment]
## TODO
- [ ] study sheldom ML
